version: "3"

networks:
  default:

services:
  debian:
    image: ${DOCKER_IMAGE}
    # Minimal HTTP server
    command: ncat -l 80 -k -c "echo 'HTTP/1.1 200 OK\n\n $$(date)'"
    environment:
      - ENTRYPOINT_DEBUG=true
      - LC_COLLATE=cs_CZ.UTF-8
      - LOG_FILE=/var/log/docker.log
      - ERR_FILE=/var/log/docker.err
    networks:
      default:
        aliases:
          - debian.local

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - debian
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - ENTRYPOINT_DEBUG=true
      # Wait until the tested container is started
      - WAIT_FOR_URL=http://debian.local
      - WAIT_FOR_TIMEOUT=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - debian
    environment:
      - ENTRYPOINT_DEBUG=true
      # Wait until the tested container is started
      - WAIT_FOR_URL=http://debian.local
      - WAIT_FOR_TIMEOUT=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  test_project_dir:
